name: Bug report
description: Submit a bug report
title: '[BUG]: '
labels: ['bug']
assignees: 'bbtufty'

body:
  - type: dropdown
    id: version
    attributes:
      label: Installation
      description: Are you using pip or GitHub? Which GitHub tag?
      options:
        - pip
        - GitHub - main branch
        - GitHub - dev branch
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the behavior
      description: If not present under all circumstances, give a step-by-step on how to reproduce the bug.
      value: |
        1. 
        2.
        ...
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Attach any applicable screenshots that illustrate your problem.
  - type: textarea
    id: preferences
    attributes:
      label: Preference File
      description: Paste your config file (likely config.yml), with any sensitive info redacted
      render: yaml
  - type: textarea
    id: log
    attributes:
      label: Log
      description: Attach the relevant log file(s)
