url: "https://raw.githubusercontent.com/unexpectedpanda/retool-clonelists-metadata/main/clonelists"

Nintendo - GameCube: "Nintendo - GameCube (Redump).json"
Nintendo - Nintendo Entertainment System: "Nintendo - Nintendo Entertainment System (No-Intro).json"
Nintendo - Super Nintendo Entertainment System: "Nintendo - Super Nintendo Entertainment System (No-Intro).json"
Sony - PlayStation: "Sony - PlayStation (Redump).json"
Sony - PlayStation 2: "Sony - PlayStation 2 (Redump).json"
