group: "No-Intro"
dir: "/No-Intro/Nintendo - Game Boy Color/"
unzip: false

# RetroAchievements
ra_id: 6
ra_hash_method: "md5"

# ROMPatcher
patch_method: "rompatcher.js"
file_exts:
  - ".gbc"
patch_file_exts:
  - ".bps"
