group: "No-Intro"
dir: "/No-Intro/Nintendo - Virtual Boy/"
unzip: false
file_exts:
  - ".vb"

# RetroAchievements
ra_id: 28
ra_hash_method: "md5"

# EmulationStation Friendly Name
es_friendly_name: "vb"