group: "No-Intro"
dir: "/No-Intro/Nintendo - Game Boy Advance/"
unzip: false
file_exts:
  - ".gba"

# RetroAchievements
ra_id: 5
ra_hash_method: "md5"

# ROMPatcher
patch_method: "rompatcher.js"
patch_file_exts:
  - ".bps"
