group: "No-Intro"
dir: "/No-Intro/Nintendo - Pokemon Mini/"
unzip: false
file_exts:
  - ".min"

# RetroAchievements
ra_id: 24
ra_hash_method: "md5"

#EmulationStation Friendly Name
es_friendly_name: "pm"