group: "No-Intro"
dir: "/No-Intro/Nintendo - Nintendo Entertainment System (Headered)/"
unzip: false
file_exts:
  - ".nes"

# RetroAchievements
ra_id: 7
ra_hash_method: "custom"

# ROMPatcher
patch_method: "rompatcher.js"
patch_file_exts:
  - ".ips"
