group: "No-Intro"
dir: "/No-Intro/Nintendo - Game Boy/"
unzip: false
file_exts:
  - ".gb"

# RetroAchievements
ra_id: 4
ra_hash_method: "md5"

# ROMPatcher
patch_method: "rompatcher.js"
patch_file_exts:
  - ".bps"
