group: "No-Intro"
dir: "/No-Intro/Nintendo - Super Nintendo Entertainment System/"
unzip: false
file_exts:
  - ".sfc"

# RetroAchievements
ra_id: 3
ra_hash_method: "md5"

# ROMPatcher
patch_method: "rompatcher.js"
patch_file_exts:
  - ".bps"
