group: "No-Intro"
dir: "/No-Intro/Nintendo - Nintendo 64 (BigEndian)/"
unzip: false

# RetroAchievements
ra_id: 2
ra_hash_method: "md5"

# ROMPatcher
patch_method: "rompatcher.js"
file_exts:
  - ".z64"
patch_file_exts:
  - ".bps"
