group: "No-Intro"
dir: "/No-Intro/Nintendo - Nintendo Entertainment System (Headered)/"
unzip: false

# RetroAchievements
ra_id: 7
ra_hash_method: "custom"

# ROMPatcher
patch_method: "rompatcher.js"
file_exts:
  - ".nes"
patch_file_exts:
  - ".ips"
