group: "No-Intro"
dir: "/No-Intro/Nintendo - Super Nintendo Entertainment System/"
unzip: false

# RetroAchievements
ra_id: 3
ra_hash_method: "custom"

# ROMPatcher
patch_method: "rompatcher.js"
file_exts:
  - ".sfc"
patch_file_exts:
  - ".bps"
