group: "No-Intro"
dir: "/No-Intro/Sega - Mega Drive - Genesis/"
unzip: false
file_exts:
  - ".md"

# RetroAchievements
ra_id: 1
ra_hash_method: "md5"

# ROMPatcher
patch_method: "rompatcher.js"
patch_file_exts:
  - ".bps"
