group: "Redump"
dir: "/Redump/Sony - PlayStation/"
unzip: false
file_exts:
  - ".bin"
  - ".cue"
compress: true
compress_method: "chdman"
compress_file_exts:
  - ".chd"

subchannels:
  SBI: "/Redump/Sony - PlayStation - SBI Subchannels/"

# RetroAchievements
ra_id: 12
ra_hash_method: "custom"
