group: "Redump"
dir: "/Redump/Sony - PlayStation/"
unzip: true
file_exts:
  - ".bin"
  - ".cue"

additional_dirs:
  SBI: "/Redump/Sony - PlayStation - SBI Subchannels/"

# RetroAchievements
ra_id: 12
ra_hash_method: "custom"
