Nintendo - Game Boy:
  file_mapping: "Nintendo - Game Boy (*)"

Nintendo - Game Boy Color:
  file_mapping: "Nintendo - Game Boy Color (*)"

Nintendo - Game Boy Advance:
  file_mapping: "Nintendo - Game Boy Advance (*)"

Nintendo - Pokemon Mini:
  file_mapping: "Nintendo - Pokemon Mini (*)"

Nintendo - Nintendo Entertainment System:
  file_mapping: "Nintendo - Nintendo Entertainment System (Headered) (*)"

Nintendo - Super Nintendo Entertainment System:
  file_mapping: "Nintendo - Super Nintendo Entertainment System (*)"

Nintendo - Nintendo 64:
  file_mapping: "Nintendo - Nintendo 64 (BigEndian) (*)"

Sega - Mega Drive - Genesis:
  file_mapping: "Sega - Mega Drive - Genesis (*)"