Nintendo - Nintendo Entertainment System:
  file_mapping: "Nintendo - Nintendo Entertainment System (Headered)"

Nintendo - Super Nintendo Entertainment System:
  file_mapping: "Nintendo - Super Nintendo Entertainment System"