name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build_sdist_and_wheel:
    name: Build source distribution
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Versions listed at https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version: [
          "3.11",
          "3.12",
        ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Run pytest
        run: |
          sudo apt update && sudo apt install -y libegl1-mesa-dev
          pip install -e .
          pip install pytest
          cd tests
          pytest tests_romparser.py
          pytest tests_romchooser.py
